app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Main
Route::get('/', function () {
    return view('layouts/home');
});

//Authentication
Route::get('auth/logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout']);
Route::controllers(['auth' => 'Auth\AuthController']);
//Route::post('auth/login', 'Auth\AuthController@postLogin');

// Checklists and Tasks
Route::resource('/checklists', 'ChecklistController');
Route::resource('checklists.tasks', 'TaskController');

//Api
Route::group(['prefix' => 'api', 'namespace' => 'Api', 'middleware' => 'auth'], function() {
    Route::resource('checklists', 'ChecklistControllerApi');
});

app/Checklist.php
<?php namespace App;


use Illuminate\Database\Eloquent\Model;


class Checklist extends Model
{
    protected $table = 'checklists';

    protected $fillable = ['name', 'summary', 'priority'];

    protected $dates = ['created_at', 'updated_at'];

    public function tasks()
    {
        return $this->hasMany('App\Task');
    }

    public function users()
    {
        return $this->belongsToMany('App\User');
    }

    public function scopeOwned($query)
    {
        $ownerRole = Role::where('name','owner')->first();
        return $query->where("role_id",'=',$ownerRole->id);
    }

    public function scopeEditable($query)
    {
        $editorRole = Role::where('name','editor')->first();
        return $query->where("role_id",'=',$editorRole->id);
    }

    public function scopeReadable($query)
    {
        $readerRole = Role::where('name','reader')->first();
        return $query->where("role_id",'=',$readerRole->id);
    }

    public function owner()
    {
        $roleId = Role::where('name','=', 'owner')->first()->id;
        return $this->belongsToMany('App\User')
            ->where('role_id',$roleId);
    }

    public function editors()
    {
        $roleId = Role::where('name','=', 'editor')->first()->id;
        return $this->belongsToMany('App\User')
            ->where('role_id',$roleId);
    }

    public function readers()
    {
        $roleId = Role::where('name','=', 'reader')->first()->id;
        return $this->belongsToMany('App\User')
            ->where('role_id',$roleId);
    }

}

app/Http/Controllers/ChecklistController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests\ChecklistRequest;
use Illuminate\Http\Request;
use App\Checklist;
use App\Role;

class ChecklistController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $checklistsOwned = \Auth::user()->checklistsOwned;
        $checklistsEditable = \Auth::user()->checklistsCanEdit;
        $checklistsReadable = \Auth::user()->checklistsCanOnlyRead;
        return view('checklists.index', compact('checklistsOwned','checklistsEditable','checklistsReadable'));
    }

    public function show($id)
    {
        $checklist = Checklist::findOrFail($id);

        if (\Auth::user()->cannot('access', $checklist)) {
            return redirect('checklists');
        }
        $tasks = $checklist->tasks;
        return view('checklists.show', compact('checklist', 'tasks'));
    }

    public function create()
    {
        $user = \Auth::user();
        return view('checklists.create', compact('user'));
    }

    public function store(ChecklistRequest $request)
    {
        $checklist = Checklist::create($request->all());
        $checklist->users()->sync([\Auth::user()->id => ['role_id' => Role::where("name","=","owner")->first()->id]]);
        return redirect('/checklists');
    }

    public function destroy($id)
    {
        $checklist = Checklist::findOrFail($id);
        if (\Auth::user()->cannot('access-as-owner', $checklist)) {
            return redirect('checklists');
        }
        $checklist->delete();
        return redirect('/checklists');
    }

    public function edit($id)
    {
        $checklist = Checklist::findOrFail($id);
        $tasks = $checklist->tasks;
        if (\Auth::user()->cannot('access-as-owner',$checklist) && \Auth::user()->cannot('access-as-editor', $checklist)) {
            return redirect('checklists');
        }
        return view('checklists.edit', compact('checklist', 'tasks'));
    }

    public function update($id, ChecklistRequest $request)
    {
        $checklist = Checklist::findOrFail($id);
        if (\Auth::user()->cannot('access-as-owner',$checklist) && \Auth::user()->cannot('access-as-editor', $checklist)) {
            return redirect('checklists');
        }
        $checklist->update($request->all());
        return redirect('/checklists');
    }

}

resources/views/checklists/_form.blade.php
<script src="/js/formEdit.js"></script>

<div id="formContainer" class="form-horizontal">
    <div id="nameDiv" class="form-group">
        {!! Form::label('name', 'Name:') !!}
        <div class="row">
            <div class="col-xs-5">
                <p>{{$checklist->name}}</p>
            </div>
            <div class="col-xs-5">
                {!! Form::text('name', null, ['class'=>'form-control stick-to-right']) !!}
            </div>
            <div class="col-xs-2">
                <input type="button" class="padded-left" data-type="name" name="formEntryRevert" value="Revert">
            </div>
        </div>
    </div>

    <div id="summaryDiv" class="form-group">
        {!! Form::label('summary', 'Summary:') !!}
        <div class="row">
            <div class="col-xs-5">
                <p>{{$checklist->summary}}</p>
            </div>
            <div class="col-xs-5">
                {!! Form::textarea('summary', null, ['class'=>'form-control']) !!}
            </div>
            <div class="col-xs-2">
                <input type="button" class="padded-left" data-type="summary" name="formEntryRevert" value="Revert">
            </div>
        </div>
    </div>

    <div id="priorityDiv" class="form-group">
        {!! Form::label('priority', 'Priority:') !!}
        <div class="row">
            <div class="col-xs-5">
                <p>{{$checklist->priority}}</p>
            </div>
            <div class="col-xs-5">
                {!! Form::number('priority', null, ['class'=>'form-control']) !!}
            </div>
            <div class="col-xs-2">
                <input type="button" class="padded-left" data-type="priority" name="formEntryRevert" value="Revert">
            </div>
        </div>
    </div>

    <div class="form-group">
        {!! Form::submit($submitButtonName, ['class'=>'btn btn-primary form-control']) !!}
    </div>

    <div class="form-group">
        <a class="btn btn-default form-control" href="{{ route('checklists.index') }}">
            Back to checklists
        </a>
    </div>
</div>

resources/views/checklists/_show.blade.php
<style>
    a, a:hover, a:visited, a:active {
        color:inherit;

    }
</style>

<h2>Checklist: {{$checklist->name}}</h2>
<ul>
    <li><strong>Summary:</strong> {{ $checklist->summary }}</li>
</ul>

@if($tasks->isEmpty())
    <p>No tasks.</p>
@endif

<table class="table table-striped">
    <thead>
    <tr>
        <th>Name</th>
        <th>Details</th>
        <th>Priority</th>
    </tr>
    </thead>
    <tbody>
    @foreach ($tasks as $task)
        <tr>
            <td>{{ $task->name }}</td>
            <td>{{ $task->details }}</td>
            <td>{{ $task->priority }}</td>
            <td>
                <a href="{{ route('checklists.tasks.edit', [$checklist->id, $task->id]) }}" value="Edit"><input type="button" value="Edit"></a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/checklists/create.blade.php
@extends('layouts.app')

@section('content')
    <h1>Checklist</h1>
    {!! Form::open(['route' => 'checklists.store']) !!}

    @include('checklists._form',["submitButtonName" => "Add Checklist"]);

    {!! Form::close() !!}
@endsection

resources/views/checklists/edit.blade.php
@extends('layouts.app')

@section('content')
    <style>
        a, a:hover, a:visited, a:active {
            color:inherit;

        }
    </style>

    <h1>Checklist</h1>
    {!! Form::model($checklist, ['method' => 'PUT', 'route' => ['checklists.update', $checklist->id]]) !!}

    @include('checklists._form',["checklist" => $checklist, "submitButtonName" => "Update Checklist"])

    {!! Form::close() !!}

    <h3>Tasks</h3>

    <a href="{{ route('checklists.tasks.create', $checklist->id) }}">Add an task</a>

    @if($tasks->isEmpty())
        <p>No tasks.</p>
    @else
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Details</th>
                <th>Priority</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($tasks as $task)
                <tr>
                    <td>{{ $task->name }}</td>
                    <td>{{ $task->details }}</td>
                    <td>{{ $task->priority }}</td>
                    <td>
                        <a href="{{ route('checklists.tasks.edit', [$checklist->id, $task->id]) }}"><input type="button" value="Edit"></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif
@endsection

resources/views/checklists/index.blade.php
@extends('layouts.app')

@section('content')
    <script src="js/checklistView.js"></script>
    <style>
        a, a:hover, a:visited, a:active {
            color:inherit;

        }
    </style>

    <h2>Checklists</h2>
    <p><a href="{{ url('/checklists/create') }}">Add a Checklist</a></p>

    @if ($checklistsEditable->count() == 0 && $checklistsReadable->count() == 0)
        <p>There are no checklists in the system.</p>
    @else
        <div class="checklistTables">
        <table class="table table-striped">
            <h4>Checklists you own</h4>
            <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($checklistsOwned as $checklist)
                <tr>
                    <td>{{ $checklist->name }}</td>
                    <td>{{ $checklist->summary }}</td>
                    <td>
                        <input type="button" data-checklistId="{{$checklist->id}}" class="viewChecklist" value="View"> -
                        <a  href="{{ route('checklists.edit', $checklist->id) }}"><input type="button" value="Edit"></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        <table class="table table-striped">
            <thead>
            <h4>Others' checklists you can edit</h4>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($checklistsEditable as $checklist)
                <tr>
                    <td>{{ $checklist->name }}</td>
                    <td>{{ $checklist->summary }}</td>
                    <td>
                        <input type="button" data-checklistId="{{$checklist->id}}" class="viewChecklist" value="View"> -
                        <a  href="{{ route('checklists.edit', $checklist->id) }}"><input type="button" value="Edit"></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        <table class="table table-striped">
            <thead>
            <h4>Checklists you can only view</h4>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($checklistsReadable as $checklist)
                <tr>
                    <td>{{ $checklist->name }}</td>
                    <td>{{ $checklist->summary }}</td>
                    <td>
                        <input type="button" data-checklistId="{{$checklist->id}}" class="viewChecklist" value="View Only">
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        </div>
    @endif

    <div class="padded-top">
        <input id="checklistViewHide" class="stick-to-right" style="display:none" type="button" value="Hide">
        <div id="checklistView" style="display:none">

        </div>
    </div>

@endsection

resources/views/checklists/show.blade.php
@extends('layouts.app')

@section('content')
    <style>
        a, a:hover, a:visited, a:active {
            color:inherit;

        }
    </style>
    <h2>Checklist: {{$checklist->name}}</h2>

    <ul>
        <li><strong>Summary:</strong> {{ $checklist->summary }}</li>
    </ul>

    <a href="{{ route('checklists.index') }}"><input type="button" value="Back to checklists"></a>

    <h3>Tasks</h3>

    <a href="{{ route('checklists.tasks.create', $checklist->id) }}"><input type="button" value="Add a task"></a>

    @if($tasks->isEmpty())
        <p>No tasks.</p>
    @endif

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Name</th>
            <th>Details</th>
            <th>Priority</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($tasks as $task)
            <tr>
                <td>{{ $task->name }}</td>
                <td>{{ $task->details }}</td>
                <td>{{ $task->priority }}</td>
                <td>
                    <a href="{{ route('checklists.tasks.edit', [$checklist->id, $task->id]) }}"><input type="button" value="Edit"></a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection