app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Main
Route::get('/', function () {
    return view('layouts/home');
});

//Authentication
Route::get('auth/logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout']);
Route::controllers(['auth' => 'Auth\AuthController']);
//Route::post('auth/login', 'Auth\AuthController@postLogin');

// Checklists and Tasks
Route::resource('/checklists', 'ChecklistController');
Route::resource('checklists.tasks', 'TaskController');

//Api
Route::group(['prefix' => 'api', 'namespace' => 'Api', 'middleware' => 'auth'], function() {
    Route::resource('checklists', 'ChecklistControllerApi');
});

app/Task.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $table = 'tasks';

    protected $fillable = ['name', 'checklist_id', 'details', 'priority'];

    protected $dates = ['created_at', 'updated_at'];

    public function checklist()
    {
        return $this->belongsTo('App\Checklist');
    }
}

app/Http/Controllers/TaskController.php
<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Task;
use App\Checklist;

class TaskController extends Controller
{
    public function create($checklistID)
    {
        $checklist = Checklist::findOrFail($checklistID);
        $tasks = $checklist->tasks;
        return view('tasks.create', compact('checklist', 'tasks'));
    }

    public function store(Request $request)
    {
        $requirements = $request->only('name', 'details','priority');
        foreach($requirements as $req)
        {
            if ($req == null)
            {
                return redirect('checklists/'.$request->checklist_id.'/tasks/create')
                    ->withErrors('Please enter information into all required fields');
            }
        }
        $task = Task::create($request->all());
        return redirect()->route('checklists.show', [$task->checklist_id]);
    }

    public function update(Request $request)
    {
        $task = Task::find($request->id);
        $task->update($request->all());
        return redirect()->route('checklists.show', [$task->checklist_id]);
    }

    public function destroy($id)
    {
        $checklist = Checklist::find($id);
        if (\Auth::user()->cannot('access-as-owner', $checklist)) {
            return redirect('checklists');
        }
        $checklist->delete();
        return redirect('/checklists');
    }

    public function edit($listId, $taskId)
    {
        $task = Task::findOrFail($taskId);
        $checklist = Checklist::findOrFail($listId);
        if (\Auth::user()->cannot('access-as-owner',$checklist) && \Auth::user()->cannot('access-as-editor', $checklist)) {
            return redirect('checklists');
        }
        return view('tasks.edit', compact('task', 'checklist'));
    }
}

resources/views/tasks/_form.blade.php
@extends('layouts.app')

<script src="/js/formEdit.js"></script>

<div class="form-group">
    {!! Form::hidden('checklist_id', $checklist->id) !!}
</div>

<div id="formContainer" class="form-horizontal">
    <div id="nameDiv" class="form-group">
        {!! Form::label('name', 'Name:') !!}
        <div class="row">
            <div class="col-xs-5">
                <p>{{$task->name}}</p>
            </div>
            <div class="col-xs-5">
                {!! Form::text('name', null, ['class'=>'form-control stick-to-right']) !!}
            </div>
            <div class="col-xs-2">
                <input type="button" class="padded-left" data-type="name" name="formEntryRevert" value="Revert">
            </div>
        </div>
    </div>

    <div id="detailsDiv" class="form-group">
        {!! Form::label('details', 'Details:') !!}
        <div class="row">
            <div class="col-xs-5">
                <p>{{$task->details}}</p>
            </div>
            <div class="col-xs-5">
                {!! Form::textarea('details', null, ['class'=>'form-control']) !!}
            </div>
            <div class="col-xs-2">
                <input type="button" class="padded-left" data-type="details" name="formEntryRevert" value="Revert">
            </div>
        </div>
    </div>

    <div id="priorityDiv" class="form-group">
        {!! Form::label('priority', 'Priority:') !!}
        <div class="row">
            <div class="col-xs-5">
                <p>{{$task->priority}}</p>
            </div>
            <div class="col-xs-5">
                {!! Form::number('priority', null, ['class'=>'form-control']) !!}
            </div>
            <div class="col-xs-2">
                <input type="button" class="padded-left" data-type="priority" name="formEntryRevert" value="Revert">
            </div>
        </div>
    </div>
</div>

<div class="form-group">
    {!! Form::submit($submitButtonName, ['class'=>'btn btn-primary form-control']) !!}
</div>

<div class="form-group">
    <a class="btn btn-default form-control" href="{{ url('/checklists/'.$checklist->id) }}">
        Back to Tasks
    </a>
</div>

<!--
<div class="form-group"> {{--
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class'=>'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('details', 'Details:') !!}
    {!! Form::textarea('details', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('priority', 'Priority:') !!}
    {!! Form::number('priority', null) !!}
</div>  --}}  -->

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')
    <h1>Create Task for Checklist</h1>

    <h2>Checklist Name:</h2>
    {{ $checklist->name }}

    <h2>Task</h2>
    {!! Form::open(['route' => 'checklists.tasks.store']) !!}

    {!! Form::hidden('checklist_id', $checklist->id) !!}

    @include("tasks._form",["submitButtonName" => "Add Task"]);

    {!! Form::close() !!}
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
    <div>
        <h2>Checklist Name:<br />{{ $checklist->name }}</h2>
        <a href="{{ route('checklists.index') }}"><input type="button" value="Back to checklists"></a>
    </div>

    {!! Form::model($task, ['method' => 'PUT', 'route' => ['checklists.tasks.update', $checklist->id, $task->id]]) !!}

    {!! Form::hidden('id', $task->id) !!}

    @include("tasks._form",["submitButtonName" => "Update Task"]);

    {!! Form::close() !!}
@endsection